name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libmicrohttpd-dev # Instala CMake y libmicrohttpd
        # Clonar y compilar Prometheus Client C
        git clone https://github.com/digitalocean/prometheus-client-c.git lib/prometheus-client-c
        cd lib/prometheus-client-c
        mkdir build && cd build
        cmake ..
        make
        sudo make install

    - name: Configure
      run: cmake -S . -B build # Configura el proyecto

    - name: Build
      run: cmake --build build # Compila el proyecto

    # Opcional: Si tienes pruebas configuradas, puedes incluir este paso
    - name: Run Tests
      run: cd build && make check
