name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install CMake
      run: sudo apt-get install -y cmake # Instala CMake

    

    # Si tienes pruebas y quieres ejecutarlas, puedes incluir este paso
    - name: Run Tests
      run: cd build && make check # Reemplaza esto si no tienes un target de 'check'

